### ISSUE TITLE
Cannot read property '$moment' of undefined

### ISSUE THREAD

**Issue by blackinitial** [nuxt-community/moment-module#14]
how to use nuxt moment?

i was added nuxt moment on module nuxt.config.js and i try to call moment on mounted() a page but has undefined $moment.

nuxt.config.js
```js
modules: [
    ...
    '@nuxtjs/moment',
    ...
  ],

```
pages
```js
mounted() {
    console.log(this.$moment) // undefined $moment
  },

```

**Comment by teledirigido** [comment]
Make sure you did installed Nuxt Moment:
`yarn add moment @nuxtjs/moment` OR `npm i moment @nuxtjs/moment`

**Comment by blackinitial** [comment]
@teledirigido i was installed `@nuxtjs/moment` and `moment`

**Comment by ricardogobbosouza** [comment]
@blackinitial I could not reproduce. Share your setup

**Comment by blackinitial** [comment]
@ricardogobbosouza i use default setup from fresh nuxtjs . Only add moment on modules `nuxt.config.js`

**Comment by ricardogobbosouza** [comment]
@blackinitial Try re-install dependencies

**Comment by ricardogobbosouza** [comment]
@blackinitial it worked?

**Comment by blackinitial** [comment]
I canceled using this library, I was removed. 
Finally, I implement moment with plugin methods nuxt js.

**Comment by ricardogobbosouza** [comment]
@manniL , @pi0 
This can also be closed, this error no longer exists

**Comment by Shifu33** [comment]
Hi!

After getting this error with all my modules, i upgrade my version of npm and now it's working
I hope this can be helpful !

(same for yarn if you using it)

**Comment by PayteR** [comment]
same error here, when i call function in template 
```
{{ $moment(post.post_date).format('HH:mm') }} // works well
```
it works just fine, when it's used in mounted() it's fine too
```
  mounted: function() {
    console.log(this.$moment) // works well
  },
```
but when i want to use it in apollo query variable, then it's undefined
```
apollo: {
    posts: {
      query() {
        return POSTS_QUERY
      },
      update: data => data.postsElastic,
      variables() {
        // Use vue reactive properties here
        return {
          date_after: this.$moment().format() // undefined
        }
      }
    }
  }
```
