### ISSUE TITLE
moment module doesn't work in my nuxt project

### ISSUE THREAD

**Issue by tetreault** [nuxt-community/moment-module#2]
I added in the moment module, didn't even use it yet just added it in to the modules array in `nuxt.config.js`. I re-ran `npm run dev` and refreshed the page and all i see is `Cannot GET /`. I know the moment module caused this because its resolved immediately by removing it. 

Whats going wrong here? 

Misc info: 
- nuxt: ^1.0.0
- nuxtjs/moment: ^1.0.0

**Comment by tetreault** [comment]
@Kimel1 i just used the standard moment module instead of the nuxtjs one and it worked out fine, so id suggest going that route.

**Comment by Kimel1** [comment]
@tetreault I'm using standard module too, it works fine.

**Comment by tetreault** [comment]
@pi0 or anyone else maintaining this module -- do you have any insight in regards to the above? also this seems easily reproducible so how should i go about making a fix and PR for it when i have the time if this module isnt maintained by nuxt-community

**Comment by nomadoda** [comment]
I'm having the very same problem..

**Comment by tetreault** [comment]
so it seems like this module doesn't work for anyone then :( at least we have the standard node module.

**Comment by robsontenorio** [comment]
NUXT 1.4.1

![captura de tela 2018-07-15 as 13 28 21](https://user-images.githubusercontent.com/118955/42735918-fe9b0430-8832-11e8-8016-21d0283fcb32.png)

**Comment by shealan** [comment]
You have to `yarn add moment` as well.

**Comment by pi0** [comment]
Hi. Anyone, please add this Note to the README? I would really appreciate it 👍

**Comment by robsontenorio** [comment]
@pi0 is this should not be automatically added as a module dependency? 

Like @nuxtjs/axios and many others we don't need to include "axios" as a manual dependency on `package.json`

**Comment by pi0** [comment]
With next release moment will be a package dependency :)
