### ISSUE TITLE
Error: MomentLocalesPlugin: Moment.js doesn’t include a locale you specified: de-ch. 

### ISSUE THREAD

**Issue by Jones-S** [nuxt-community/moment-module#25]
Hi

I use the nuxt moment module like this:
```
modules: [
    '@nuxtjs/proxy',
    '@nuxtjs/axios',
    ['@nuxtjs/moment', { locales: ['de-ch'], defaultLocale: 'de-ch' }],
    ...
```
Which seems to work, but as soon as I change something to the nuxt.config.js I get the following error:

> Error: MomentLocalesPlugin: Moment.js doesn’t include a locale you specified: de-ch. Check the plugin’s `localesToKeep` option. You can see the full list of locales that Moment.js includes in node_modules/moment/locale/

I think the locales array is actually the `localesToKeep`, am I right?
So it is actually not missing..

I also checked the locale itself. Normally I would expect it to be `de-CH` but moment has a file `de-ch` in which it is also called directly `de-ch` – all lowercase.
Changing the locale to 'de' does not resolve the issue either.

What am I missing?
Thanks for your help.

**Comment by sonnh58** [comment]
same issue

**Comment by Kinvaras** [comment]
Hi,

This issue is caused by **moment-locales-webpack-plugin**. The plugin checks whether the locales you provided as an array exist as legit locales **or** one of them is set as the current moment locale. And this is the second premise that causes the error because on the first build, everything is ok, but not on further HMR (moment already has a locale "de-ch" set). I am looking for a clean workaround actually

**Comment by Kinvaras** [comment]
Well if this is a blocking issue for you (I mean, being forced to stop and start manually again and again  IS some sort of blocking issue to me :D), their is a temporary workaround:

Just create your own module:

```js
// modules/moment-reset.js
import moment from 'moment';

module.exports = function momentResetModule(moduleOptions) {
  moment.locale('en');
};
```

And inject it in your nuxt.config.js _modules_ property **BEFORE** you inject **@nuxtjs/moment**:

```js
// nuxt.config.js
module.exports = {
  // ...
  modules: [
    // ...
    '@/modules/moment-reset',
   [ '@nuxtjs/moment', ['de-ch']],
    // ...
  ],
  // ...
};
```

This simple module is in charge of resetting your moment instance to the "en" locale (which is built into moment by default). I guess you have your own plugin to initiate moment to your desired locale (in your case "de-ch").

If you have a better workaround, this would be interesting ;)

Thx,
Panday

**Comment by Jones-S** [comment]
I thought things maybe have changed since the docs now say to use buildModules and I thought there was an update on this issue.
> https://github.com/nuxt-community/moment-module

The problem still remains though. 
I added your moment-reset and at least for the first rebuild it worked. I hope it continues to do so.

**Comment by mrleblanc101** [comment]
Any update on this ?

**Comment by ricardogobbosouza** [comment]
A temporary solution would be to reset the locale before `moment-locales-webpack-plugin`

Including this snippet
```js
const moment = require('moment')
moment.locale('en')
```
 in https://github.com/nuxt-community/moment-module/blob/master/lib/module.js#L21

...

Let's wait https://github.com/iamakulov/moment-locales-webpack-plugin/issues/23

**Comment by frbuceta** [comment]
something new? official?

**Comment by ricardogobbosouza** [comment]
@frbuceta waiting https://github.com/iamakulov/moment-locales-webpack-plugin/issues/23

**Comment by frbuceta** [comment]
> @frbuceta waiting [iamakulov/moment-locales-webpack-plugin#23](https://github.com/iamakulov/moment-locales-webpack-plugin/issues/23)

I'm sorry, I hadn't seen it

**Comment by ricardogobbosouza** [comment]
@frbuceta if you update your dependencies it must have been fixed

**Comment by ricardogobbosouza** [comment]
Fixed https://github.com/iamakulov/moment-locales-webpack-plugin/releases/tag/v1.1.2

**Comment by frbuceta** [comment]
thanks ;)

**Comment by mrleblanc101** [comment]
This was closed but no new version was published ?

**Comment by ricardogobbosouza** [comment]
@mrleblanc101 don't need a new version, just update the dependencies

This has been fixed directly in [moment-locales-webpack-plugin](https://github.com/iamakulov/moment-locales-webpack-plugin/releases/tag/v1.1.2)

**Comment by mrleblanc101** [comment]
Ok, I thought you needed to bump the version in package.json from a commit I saw #50  `chore(deps): update dependency moment-locales-webpack-plugin to ^1.1.2`
