### ISSUE TITLE
Webpack dependency at runtime.

### ISSUE THREAD

**Issue by blowsie** [nuxt-community/moment-module#30]
I am unable to use this module in production with `nuxt-start` becuase the module uses
`moment-locales-webpack-plugin`. 

`moment-locales-webpack-plugin` requires webpack, which is a build time dependency rather than a runtime dependency. 

As a result, when I use `npm install --production` & `nuxt-start` this module fails since `webpack` is not available.

How can this issue be addressed?  
Is the dependency this way by design? Perhaps using this in production hadn't been considered?

**Comment by bart** [comment]
Exact same issue here. Any solution?

**Comment by blowsie** [comment]
Nope, not as of yet, 
I asked in the nuxt discord and the majority of people just said to use https://date-fns.org/. Not really the answer i was looking for but its an option at least.

**Comment by bart** [comment]
What I did for the time beeing is added webpack to package.json via `npm install webpack --save`

**Comment by pi0** [comment]
Using the latest nuxt, you can simply add this module to the `buildModules` (instead of `modules`) in `nuxt.config.js`. I'll update README as well :)
