### ISSUE TITLE
Add moment-timezone support

### ISSUE THREAD

**Issue by bernardocs** [nuxt-community/moment-module#33]
I'm assuming that there's no support for the given feature (since I've browsed a lot to find such solution - to no avail).

So... there is a way of using it?
Do you guys have any suggestion?

**Comment by edum18** [comment]
+1 need this feature too

**Comment by binaryweavers** [comment]
+1 yes please, add timezone support

**Comment by zachheine** [comment]
+1

**Comment by pi0** [comment]
PR is much welcome.  I think it should be an optional feature as of overhead. Also for timezone data, we need tree-shaking: https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin

**Comment by ricardogobbosouza** [comment]
You can use it as a plugin with this PR #45 
Depending on your needs use https://github.com/gilmoreorless/moment-timezone-data-webpack-plugin as @pi0  said
@ pi0 think we should have an option to register `moment-timezone-data-webpack-plugin`` automatically?

**Comment by pi0** [comment]
@ricardogobbosouza Yep. I think built-in support for the time-zone can be less error-prune.
