### ISSUE TITLE
[i18n] Set locale with dropdown

### ISSUE THREAD

**Issue by ozergul** [nuxt-community/moment-module#39]
Hello
Setting locale with dropdown not working properly I think. Can you give me example how can I set current locale?

**Comment by pi0** [comment]
Hi. This issue is not complete. Please at least share how are you implementing your drop-down to handle multiple locales so we can help :)

**Comment by ozergul** [comment]
Problem solved. :)

plugins/i18n.js

``` javascript
import moment from 'moment';

export default function ({ app }) {
  app.i18n.beforeLanguageSwitch = (oldLocale, newLocale) => {
    app.$moment.locale(newLocale);
  };
}

```
