### ISSUE TITLE
Filter functionality

### ISSUE THREAD

**Issue by zachheine** [nuxt-community/moment-module#40]
Is there any plan to add functionality similar to https://github.com/brockpetrie/vue-moment?

If not, is there a way to use them together (`vue-moment` also uses `this.$moment`)?

**Comment by pi0** [comment]
Hi @zachheine. You can already use `$moment` in your templates (and yes, it is reactive!):

```html
<div v-text="$moment(...)"></div>
<div>{{ $moment(...) }}</div>
```

**Comment by zachheine** [comment]
Thanks @pi0.  With `vue-moment` I was using the filter syntax (`{{ event.start | moment('dddd, MMMM Do, h:mm a') }}`) which I think is slightly more readable but this works too!
