### ISSUE TITLE
SSR makes it unable set moment object in created hook. 

### ISSUE THREAD

**Issue by abdulladev1995** [nuxt-community/moment-module#43]
Hi. I am using NUXT, [moment nuxt plugin](https://www.npmjs.com/package/@nuxtjs/moment) and Vuex store to set my initial dates. I have realized that when I use `created` hook Nuxt calls the script both client and server side(I know this behavior noted in documentation). 

**Problem** - on image you can see that on created hook on the server side (before client side ) script run and set the store value as `string` not as moment `object`. So in template section of Vue component I can not use `{{ calendarShowingDate.format('MMMM') }}` because of on server side moment hasn't set as object but it has been set as converted date string. 

**Question 1** - how to prevent this behavior of nuxt?
**Question 2** - how to set moment as object on SSR?

**Temporary fix** - On created I am formatting moment if it come from SSR `this.calendarShowingDate    ? this.setCalendarShowingDate(this.$moment(this.calendarShowingDate)) : this.setCalendarShowingDate(this.$moment());`

`this.setCalendarShowingDate` - store mutation used to set value.

I can not use mounted because of DOM already rendered and `calendarShowingDate`  still empty so it will be crashed. 

![image](https://user-images.githubusercontent.com/41891278/65964753-9fcc1b80-e46e-11e9-8edd-864a93c69776.png)

**Nuxt version** - `"nuxt": "^2.9.0",`

**Comment by ricardogobbosouza** [comment]
Hi @abdulladev1995 
Please provide a repository with the issue.
