### ISSUE TITLE
Using $moment inside templates is NOT reactive

### ISSUE THREAD

**Issue by outlier89** [nuxt-community/moment-module#52]
Hi. I am using Nuxt v2.12.0 and @nuxtjs/moment  in buildmodules.

Problem: <div>{{$moment(1578147479000).fromNow()}}</div> is not reactive. 
Page has to be refershed everytime to get the correct time duration.

As per docs: 
Using inside templates
Instead of a filter, you can easily use $moment service from templates (and yes, it is reactive!).

<div v-text="$moment(...)"></div>
<div>{{ $moment(...) }}</div>

**Comment by ricardogobbosouza** [comment]
Hi @outlier89 
Docs updated https://github.com/nuxt-community/moment-module#using-inside-templates

**Comment by Dryymoon** [comment]
I have this problem too
"nuxt": "2.14.6",
"@nuxtjs/moment": "1.6.1",

{{ $moment().fromNow() }} Isn`t reactive.

How to solve this?
