### ISSUE TITLE
Dynamic locale not working as intended

### ISSUE THREAD

**Issue by ABilenduke** [nuxt-community/moment-module#55]
I am having an issue changing the locale. It seems to always switch back to the default locale. I am trying to use English and French, if I just include the 'fr' locale then it is always french and if I set default locale 'en' it is always English.

When I set the nuxt i18n locale to the other language I am also setting the $moment locale. If it is switching locales it does nothing. If I reload (it sets the locale on load, same logic) I can see the selected locale (different from the default) for a split second and it switches back.

Any idea why this is happening?

**Comment by ricardogobbosouza** [comment]
@ABilenduke Please provide a repository with the issue.

**Comment by ABilenduke** [comment]
This was my bad, I changed it to be computed using the locale from the store and it worked fine.
