### ISSUE TITLE
using moment-jalaali plugin

### ISSUE THREAD

**Issue by 01101101M** [nuxt-community/moment-module#62]
[jalaali](https://momentjs.com/docs/#/plugins/jalaali/) plugin doesn't seem to work as intended

please checkout [code-sandbox](https://codesandbox.io/s/moment-module-x2ex1)
![image](https://user-images.githubusercontent.com/38888320/80787860-e3ba0700-8b9c-11ea-802e-f916553c4abb.png)

**Comment by ricardogobbosouza** [comment]
Hi @01101101M 

What should the return be?

**Comment by 01101101M** [comment]
> Hi @01101101M
> 
> What should the return be?

as mentioned id docs https://github.com/jalaali/moment-jalaali , https://momentjs.com/docs/#/plugins/jalaali/
it should be `۱۳۹۹/۲/۱۲ is ۲۰۲/۵/۱` or `1399/2/12 is 2020/5/1`

**Comment by ricardogobbosouza** [comment]
This plugin overrides the instance of the `moment `and therefore needs an implementation manually or an update https://github.com/jalaali/moment-jalaali#nodejs

**Comment by aliwesome** [comment]
@01101101M did you solve the problem? any update on this issue? I faced same results.
