### ISSUE TITLE
Module not found: Error: Can't resolve './locale' in '...node_modules/moment/src/lib/locale'

### ISSUE THREAD

**Issue by seth100** [nuxt-community/moment-module#63]
Hi,

I have never had that warning before, but at some point (I am not sure which package of the ones I am using was updated) I started to get this error:

```sh
WARN  in ./node_modules/moment/src/lib/locale/locales.js

Module not found: Error: Can't resolve './locale' in '...node_modules/moment/src/lib/locale'
```

The only moment locale code I use is:

```js
methods: {
     formatDate(date) {
        return this.$moment(date).locale('fr').format('DD MMMM YYYY');
      }
}
```

Any help on that please?
Thanks

**Comment by arnauddsj** [comment]
Same problem here, even if don't use the local config
```
	moment: {
		locales: ["fr"]
	},
```
getting
```
 WARN  in ./node_modules/moment/src/lib/locale/locales.js                                                                                                            friendly-errors 23:24:24

Module not found: Error: Can't resolve './locale' in '***/node_modules/moment/src/lib/locale'
```
I've just installed the module so can't relate to past experience.

**Comment by snarcraft** [comment]
moment 2.24.0 seems to work fine

**Comment by iamgp** [comment]
I also get this, using 1.6.0, without even setting a locale.

**Comment by ricardogobbosouza** [comment]
Problem on moment v2.25
https://github.com/moment/moment/issues/5501
https://github.com/moment/moment/issues/5500

**Comment by josepuma** [comment]
Same here, getting the same error.

**Comment by ricardogobbosouza** [comment]
Resolve on v1.6.1

**Comment by azeezy** [comment]
Still getting this with version `1.6.1`. Managed to solve by adding the following to the `package.json` and running `yarn`:
```json
{
...
  "devDependencies": {...},
  "resolutions": {
    "moment": "2.24.0"
  }
}
```
