### ISSUE TITLE
this.$moment(...).tz is not a function

### ISSUE THREAD

**Issue by AlxZb** [nuxt-community/moment-module#64]
Hi everyone,
I trying used timezone option but I have this issue, maybe I'm load it wrong

> this.$moment(...).tz is not a function

My nuxt.config in modules is:

`['@nuxtjs/moment', {
            moment: {
                timezone: true
            }
        }],`

And I'm use:

`"@nuxtjs/moment": "^1.6.1",
"nuxt": "^2.0.0",`

Thanks for replies!

**Comment by ricardogobbosouza** [comment]
Hi @AlxZb  
Your configuration is wrong

```js
['@nuxtjs/moment', { timezone: true }]
```

**Comment by AlxZb** [comment]
@ricardogobbosouza thanks! It works now
