### ISSUE TITLE
ERROR in ./.nuxt/moment.js Module not found: Error: Can't resolve 'moment/locale/en'

### ISSUE THREAD

**Issue by bitbytebit1** [nuxt-community/moment-module#71]
Using the latest version of Nuxt 2.14.5

Followed the setup instructions:

`yarn add --dev @nuxtjs/moment`

nuxt.config.js
```
buildModules: {
['@nuxtjs/moment', 
  {
    defaultLocale: 'en',
    locales: ['en', 'se', 'fr']
  }
]
}
```

Errors: 
`An error occurred
Home page
ERROR in ./.nuxt/moment.js
Module not found: Error: Can't resolve 'moment/locale/en' in 'C:\Users\XXX\Documents\GitHub\xxxxxx\.nuxt'`

**Comment by Jessydan1** [comment]
Hey how do you fix this ?

**Comment by LangRizkie** [comment]
Need to reopen this :(
