### ISSUE TITLE
$moment is not defined inside of Nuxt JS method

### ISSUE THREAD

**Issue by sts-ryan-holton** [nuxt-community/moment-module#76]
I've recently stripped out `vue-moment` from my project in favour of the Moment module so that I can utilise timezones and settings more efficiently. I've migrated all of my HTML mentions of `moment` over to `$moment` but the ones that exist inside of my methods now throw an error that `$moment` is not defined. I've also tried prefixing the word `this`, which removes the error but then the `duration` method no longer woks.

What am I doing wrong?

```javascript
/*
** Time difference in minutes
*/
timeDiffInMinutes (start, finish) {
  const now = $moment(start)
  const end = $moment(finish)
  const duration = moment.duration(now.diff(end))
  return duration.asMinutes()
}
```

**Comment by BlakeCampbells** [comment]
It looks like you have to prefix `this` for $moment. 

The error you're getting for the duration is probably because `moment` is undefined while `this.$moment` is what you should use.
